### PR TITLE
Add update-if-contains function

### PR DESCRIPTION
**Pull request by dehli**
Hi! I thought this might be a valuable function to include in `potpuri`. If you'd like me to change the name, add additional tests, etc, just let me know! Thanks!

I was also thinking of calling it `update-if-contains`.

### CODE REVIEW

**Comment by ikitommi** [comment]
I think `assoc-if-contains` would be better, as there is already `assoc-if`.

**Comment by dehli** [comment]
Thanks @ikitommi! I went ahead and changed the function name to `update-if-contains`. Happy new year!

**Comment by ikitommi** [comment]
thanks!

**Comment by ikitommi** [comment]
`[metosin/potpuri "0.5.3"]`

**Pull request merged**
